name: Alibaba Cloud Deployment Example

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "00-alibaba-cloud-engineering-blueprint/templates/terraform/**"

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform fmt
        working-directory: 00-alibaba-cloud-engineering-blueprint/templates/terraform
        run: terraform fmt -check
      - name: Terraform init
        working-directory: 00-alibaba-cloud-engineering-blueprint/templates/terraform
        run: terraform init
      - name: Terraform plan
        working-directory: 00-alibaba-cloud-engineering-blueprint/templates/terraform
        env:
          ALICLOUD_ACCESS_KEY: ${{ secrets.ALICLOUD_ACCESS_KEY }}
          ALICLOUD_SECRET_KEY: ${{ secrets.ALICLOUD_SECRET_KEY }}
          ALICLOUD_REGION: ${{ vars.ALICLOUD_REGION }}
        run: terraform plan
